name: Procesar PDF

on:
  push:
    paths:
      - 'pdfs/**.pdf'

jobs:
  procesar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependencias
        run: pip install -r scripts/requirements.txt

      - name: Procesar PDF
        run: python scripts/procesar_pdf.py

      - name: Commit y Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add cervezas.json
          git commit -m "Actualizar cervezas.json"
          git push
